### PR TITLE
Support all entity types in typed data and GraphQL

### PR DESCRIPTION
**Pull request by Leksat**

### CODE REVIEW

**Comment by pmelab** [comment]
Thanks! Just one remark: The media item is technically not restricted to Drupal's `media` type. It also works with `data-media-type="node:article"`. Do you think we can generalise the generated API to work with all entity types?

**Comment by Leksat** [comment]
@pmelab, in current PR I completely ignored the `data-media-type` attribute because [current docs](https://amazeelabs.github.io/silverback/features/sections/#media) say
> The `data-media-type` attribute allows narrow down the list of allowed entities...

So I assumed that something like `data-media-type="image document"` possible.

No you mention `data-media-type="node:article"`, and I wonder what are all possible formats for this attribute. My best guess:
- we support `{entity-type}:{bundle}`
- or a list of `{entity-type}:{bundle}` items separated by spaces
- in case if `{entity-type}:` is omitted, we assume `media` entity type
- we don't support mixed entity types in lists (e.g. `data-media-type="node:article media:document"` is forbidden)

All correct?

**Comment by pmelab** [comment]
We support one entity type and multiple bundles. For example: `media:image video`. And omitting the entity type is not supported right now.

**Comment by Leksat** [comment]
Got it, thanks! Will update the PR.

**Comment by Leksat** [comment]
All entity types are supported now.

Tested on NOBEL. Works.

**Comment by pmelab** [comment]
Thanks! 🎆

**Pull request merged**
